server:
  port: ${port:5000}

spring:
  application:
    name: drombler-jstore


management:
  endpoints:
    web:
      base-path: '/webresources'
  endpoint:
    health:
      show-details: ALWAYS

keycloak:
  realm: "drombler-staging"
  auth-server-url: "http://127.0.0.1:8070/auth"
  ssl-required: "external"
  resource: "jstore"
  credentials:
    secret: "11111111-1111-1111-1111-111111111111"
  use-resource-role-mappings: true
  securityConstraints:
    -
      authRoles:
        - "admin"
        - "user"
      securityCollections:
        -
          name: "Managed Components"
          patterns:
            - "/v1/managed-components/*"
    -
      authRoles:
        - "admin"
      securityCollections:
        -
          name: "admin stuff"
          patterns:
            - "/admin"

jstore:
  nexus:
    endpoint: 'http://localhost:8091'
    all-repo: 'jstore'
    free-only-repo: 'jstore-free'
    paid-only-repo: 'jstore-paid'