package org.drombler.jstore.model;

public enum JStoreErrorCode {
    //@formatter:off
    JSTORE_NEXUS_CLIENT,
    JSTORE_ILLEGAL_PROPERTY,
    JSTORE_VENDOR_ID_NOT_UNIQUE,
    JSTORE_VENDOR_NOT_FOUND,
    JSTORE_UNSUPPORTED_JRE_VENDOR,
    JSTORE_UNSUPPORTED_JRE_VERSION_FORMAT,
    JSTORE_UNSUPPORTED_JAVA_SPECIFICATION_VERSION,
    JSTORE_JRE_IMPLEMENTATION_NOT_FOUND,
    JSTORE_UNKNOWN,
    NEXUS_UNKNOWN;
    //@formatter:on
}
