@startuml

!include drombler-jstore-commons.iuml


rectangle "Company 1" <<Company>>{
    cloud "Company 1 Cloud" <<Cloud>>{
        node "Company 1 Server 1" <<Server>>{
            artifact ps1 <<Private Store>>
            ps1 -up-> dj1: proxy
        }

        node "Company 1 Server 2" <<Server>>{
            artifact ci1 <<Continuous Integration Server>>
            ci1 -up-> ps1: deploys
        }
    }

    node "Company 1 Employee 1 Desktop" <<Desktop>>{
        artifact djca4.1 <<Drombler JStore Client Agent>>
        artifact djc4.1 <<Drombler JStore Client>>
        djc4.1 -up-> djca4.1: configures
        djca4.1 -up-> dj1: get updates
        djc4.1 -up-> dj1: discovers
        djca4.1 -left-> ps1: get updates
        djc4.1 -left-> ps1: discovers
    }
}

rectangle "Company 2" <<Company>>{
    cloud "Company 2 Cloud" <<Cloud>>{
        node "Company 2 Server 1" <<Server>>{
            artifact ps2 <<Private Store>>
            ps2 -up-> dj1: proxy
        }

        node "Company 2 Server 2" <<Server>>{
            artifact ci2 <<Continuous Integration Server>>
            ci2 -up-> ps2: deploys
        }
    }

    node "Company 2 Employee 1 Desktop" <<Desktop>>{
        artifact djca5.1 <<Drombler JStore Client Agent>>
        djca5.1 -left-> ps2: get updates
    }
}

rectangle "Company 3" <<Company>>{
    cloud "Company 3 Cloud" <<Cloud>>{
        node "Company 3 Server 1" <<Server>>{
            artifact ps3 <<Private Store>>
            ps3 -right-> dj1: proxy
        }

        node "Company 3 Server 2" <<Server>>{
            artifact ci3 <<Continuous Integration Server>>
            ci3 -down-> ps3: deploys
        }
    }
}

rectangle "Customer 1" <<Customer>>{
    node "Customer 1 Desktop" <<Desktop>>{
        artifact djca6.1 <<Drombler JStore Client Agent>>
        artifact djc6.1 <<Drombler JStore Client>>
        djc6.1 -down-> djca6.1: configures
        djca6.1 -down-> dj1: get updates
        djc6.1 -down-> dj1: discovers
        djca6.1 -left-> ps3: get updates
    }
}

rectangle "Company 4" <<Company>>{
    cloud "Company 4 Cloud" <<Cloud>>{
        node "Company 4 Server 1" <<Server>>{
            artifact ps4 <<Private Store>>
            ps4 -left-> dj1: proxy
        }

        node "Company 4 Server 3" <<Server>>{
            artifact djav1 <<Drombler JStore Application Vendor>>
            dj1 -left-> djav1: proxy
        }

        node "Company 4 Server 2" <<Server>>{
            artifact ci4 <<Continuous Integration Server>>
            ci4 -down-> ps4: deploys
            ci4 -down-> djav1: deploys
        }
    }

    node "Company 4 Employee 1 Desktop" <<Desktop>>{
        artifact djca7.1 <<Drombler JStore Client Agent>>
        artifact djc7.1 <<Drombler JStore Client>>
        djc7.1 -down-> djca7.1: configures
        djca7.1 -left-> dj1: get updates
        djc7.1 -left-> dj1: discovers
        djca7.1 -down-> ps4: get updates
        djc7.1 -down-> ps4: discovers
    }
}

@enduml
